/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import SQL.Insertar;
import Tools.Creador;
import java.awt.Color;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel
 */
public class Create_user extends javax.swing.JDialog {

    /**
     * Creates new form Create_folder
     */
    
    Creador crea = new Creador();
    public Create_user(JFrame padre, boolean modo){
        super(padre, modo);
        initComponents();
        this.setLocationRelativeTo(null);
        crea.llenando_JComboBox_Storage(espacio_nube);
    }
    
    private static boolean isNumeric(String cadena){
	try {
            Integer.parseInt(cadena);
            return true;
	} catch (NumberFormatException nfe){
            return false;
	}
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_create = new javax.swing.JButton();
        Jtext_nombre_user = new javax.swing.JLabel();
        JPanel_users = new javax.swing.JPanel();
        name_user = new LIB.JTexfieldPH_FielTex();
        Jtext_contraseña = new javax.swing.JLabel();
        Jpanel_Contraseña = new javax.swing.JPanel();
        name_user1 = new LIB.JTexfieldPH_FielTex();
        Jtext_espacio_nube = new javax.swing.JLabel();
        espacio_nube = new javax.swing.JComboBox<>();
        Atras = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_create.setBackground(new java.awt.Color(10, 130, 203));
        btn_create.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_create.setText("Crear");
        btn_create.setToolTipText("");
        btn_create.setBorderPainted(false);
        btn_create.setContentAreaFilled(false);
        btn_create.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_create.setFocusPainted(false);
        btn_create.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_create.setName(""); // NOI18N
        btn_create.setOpaque(true);
        btn_create.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_createMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_createMouseExited(evt);
            }
        });
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        jPanel3.add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 90, 40));

        Jtext_nombre_user.setText("Nombre de usuario");
        jPanel3.add(Jtext_nombre_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JPanel_users.setBackground(new java.awt.Color(230, 230, 230));

        name_user.setBackground(new java.awt.Color(230, 230, 230));
        name_user.setBorder(null);
        name_user.setToolTipText("");
        name_user.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        name_user.setOpaque(false);
        name_user.setPhColor(new java.awt.Color(10, 144, 203));
        name_user.setPlaceholder("Nombre usuario");
        name_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_usersLayout = new javax.swing.GroupLayout(JPanel_users);
        JPanel_users.setLayout(JPanel_usersLayout);
        JPanel_usersLayout.setHorizontalGroup(
            JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name_user, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        JPanel_usersLayout.setVerticalGroup(
            JPanel_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name_user, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jPanel3.add(JPanel_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 40));

        Jtext_contraseña.setText("Contraseña");
        jPanel3.add(Jtext_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        Jpanel_Contraseña.setBackground(new java.awt.Color(230, 230, 230));

        name_user1.setBackground(new java.awt.Color(230, 230, 230));
        name_user1.setBorder(null);
        name_user1.setToolTipText("");
        name_user1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        name_user1.setOpaque(false);
        name_user1.setPhColor(new java.awt.Color(10, 144, 203));
        name_user1.setPlaceholder("Contraseña");
        name_user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_user1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jpanel_ContraseñaLayout = new javax.swing.GroupLayout(Jpanel_Contraseña);
        Jpanel_Contraseña.setLayout(Jpanel_ContraseñaLayout);
        Jpanel_ContraseñaLayout.setHorizontalGroup(
            Jpanel_ContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_ContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name_user1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        Jpanel_ContraseñaLayout.setVerticalGroup(
            Jpanel_ContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_ContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name_user1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jPanel3.add(Jpanel_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 40));

        Jtext_espacio_nube.setText("Espacio en nube");
        jPanel3.add(Jtext_espacio_nube, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        espacio_nube.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        espacio_nube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacio_nubeActionPerformed(evt);
            }
        });
        jPanel3.add(espacio_nube, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 330));

        Atras.setBackground(new java.awt.Color(10, 144, 203));
        Atras.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_icon.png"))); // NOI18N
        Atras.setBorder(null);
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setFocusPainted(false);
        Atras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_icon_G.png"))); // NOI18N
        Atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_icon_G.png"))); // NOI18N
        Atras.setVerifyInputWhenFocusTarget(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 50, 40));

        jPanel4.setBackground(new java.awt.Color(205, 205, 205));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, 20));

        jLabel4.setBackground(new java.awt.Color(10, 144, 203));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 10));

        jLabel3.setBackground(new java.awt.Color(10, 144, 203));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("  Creación de usuario:");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createMouseEntered
        btn_create.setBackground(new Color(8,105,165));
    }//GEN-LAST:event_btn_createMouseEntered

    private void btn_createMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createMouseExited
        btn_create.setBackground(new Color(10,130,203));
    }//GEN-LAST:event_btn_createMouseExited

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        Insertar is = new Insertar();
        String username = this.name_user.getText();
        String password = this.name_user1.getText();
        String espacio = this.espacio_nube.getSelectedItem().toString();
        if (username.length()>=5){
                
                if (is.insertUser("'"+espacio.replaceAll(" GB", "")+"','NORMAL','"+username+"','"+password+"'")){
                    JOptionPane.showMessageDialog(null, "El usuario se ha creado con exito", "Completado",JOptionPane.INFORMATION_MESSAGE);
                } else JOptionPane.showMessageDialog(null, "Ha ocurrido un error al intentar registrar el usuario", "ERROR",JOptionPane.ERROR_MESSAGE);
                this.dispose();
       
        }else{
            JOptionPane.showMessageDialog(null, "El username debe contener al menos 5 caracteres", "mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_createActionPerformed

    private void name_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_userActionPerformed

    private void name_user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_user1ActionPerformed

    private void espacio_nubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacio_nubeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio_nubeActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Create_user dialog = new Create_user(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JPanel JPanel_users;
    private javax.swing.JPanel Jpanel_Contraseña;
    private javax.swing.JLabel Jtext_contraseña;
    private javax.swing.JLabel Jtext_espacio_nube;
    private javax.swing.JLabel Jtext_nombre_user;
    private javax.swing.JButton btn_create;
    private javax.swing.JComboBox<String> espacio_nube;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private LIB.JTexfieldPH_FielTex name_user;
    private LIB.JTexfieldPH_FielTex name_user1;
    // End of variables declaration//GEN-END:variables
}
