/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.FTPConnection;
import Tools.StringHandling;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel
 */
public class Load_file extends javax.swing.JDialog {

    /**
     * Creates new form Load_file
     */
    public Load_file(JFrame padre, boolean modo) {
        super(padre, modo);
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        btn_abrir.setToolTipText("Explorador de archivos");
        btn_cargar.setToolTipText("Cargar archivo");
        Atras.setToolTipText("Volver");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ruta = new LIB.JTexfieldPH_FielTex();
        btn_abrir = new javax.swing.JButton();
        btn_cargar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(230, 230, 230));

        ruta.setBackground(new java.awt.Color(230, 230, 230));
        ruta.setBorder(null);
        ruta.setToolTipText("");
        ruta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ruta.setOpaque(false);
        ruta.setPhColor(new java.awt.Color(10, 144, 203));
        ruta.setPlaceholder("Ruta de archivo");
        ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ruta, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(ruta, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 40));

        btn_abrir.setBackground(new java.awt.Color(158, 163, 165));
        btn_abrir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_abrir.setForeground(new java.awt.Color(0, 0, 0));
        btn_abrir.setText("Abrir");
        btn_abrir.setToolTipText("");
        btn_abrir.setBorderPainted(false);
        btn_abrir.setContentAreaFilled(false);
        btn_abrir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_abrir.setFocusPainted(false);
        btn_abrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_abrir.setName(""); // NOI18N
        btn_abrir.setOpaque(true);
        btn_abrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_abrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_abrirMouseExited(evt);
            }
        });
        btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirActionPerformed(evt);
            }
        });
        jPanel3.add(btn_abrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 90, 40));

        btn_cargar.setBackground(new java.awt.Color(10, 130, 203));
        btn_cargar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_cargar.setForeground(new java.awt.Color(0, 0, 0));
        btn_cargar.setText("Cargar");
        btn_cargar.setToolTipText("");
        btn_cargar.setBorderPainted(false);
        btn_cargar.setContentAreaFilled(false);
        btn_cargar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cargar.setFocusPainted(false);
        btn_cargar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cargar.setName(""); // NOI18N
        btn_cargar.setOpaque(true);
        btn_cargar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cargarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cargarMouseExited(evt);
            }
        });
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 90, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 140));

        jPanel4.setBackground(new java.awt.Color(205, 205, 205));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, 20));

        Atras.setBackground(new java.awt.Color(10, 144, 203));
        Atras.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_icon.png"))); // NOI18N
        Atras.setBorder(null);
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setFocusPainted(false);
        Atras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_icon_G.png"))); // NOI18N
        Atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_icon_G.png"))); // NOI18N
        Atras.setVerifyInputWhenFocusTarget(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 30, 30));

        jLabel4.setBackground(new java.awt.Color(10, 144, 203));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 10));

        jLabel3.setBackground(new java.awt.Color(10, 144, 203));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("  Carga de nuevo archivo:");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaActionPerformed

    private void btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirActionPerformed
        //Creamos el objeto JFileChooser
        JFileChooser fc = new JFileChooser();

        //-------------------------------------------
        //Podemos poner filtros
        //FileNameExtensionFilter filtro = new FileNameExtensionFilter(".TXT",".txt");

        //Le indicamos el filtro
        //fc.setFileFilter(filtro);
        //-------------------------------------------

        //-------------------------------------------
        //Podemos seleccionar SOLO DIRECTORIOS
        //fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //Podemos seleccionar SOLO ARCHIVOS
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //Podemos seleccionar AMBOS DIRECORIOS Y ARCHIVOS
        //fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //-------------------------------------------

        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion = fc.showOpenDialog(this);

        //Si el usuario, pincha aceptar
        if(seleccion == JFileChooser.APPROVE_OPTION){
            //Seleccionamos el fichero
            File fichero = fc.getSelectedFile();

            //Escribe la ruta del fichero seleccionado en el campo de texto
            this.ruta.setText(fichero.getAbsolutePath());

        }
    }//GEN-LAST:event_btn_abrirActionPerformed

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
        StringHandling localFile = new StringHandling();
        String file_dir = this.ruta.getText();
        File fRuta = new File(file_dir);
        
        //Verifica que es un directorio
        //if(fRuta.isDirectory()){
        if(fRuta.exists()){    

             String file_name = localFile.getFileName(file_dir);

            //JOptionPane.showMessageDialog(null, localFile.getFileName(file_dir), "mensaje",JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showMessageDialog(null, file_dir, "mensaje",JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showMessageDialog(null, file_name, "mensaje",JOptionPane.INFORMATION_MESSAGE);

            FTPConnection nuevo = new FTPConnection();

            nuevo.subirArchivo(file_dir, file_name);
        }else{
            this.ruta.setText("");
             JOptionPane.showMessageDialog(null, "Esta ruta no existe, intentelo de nuevo.", "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_cargarActionPerformed

    private void btn_abrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_abrirMouseEntered
        btn_abrir.setBackground(Color.gray);
    }//GEN-LAST:event_btn_abrirMouseEntered

    private void btn_abrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_abrirMouseExited
        btn_abrir.setBackground(new Color(158,163,165));
    }//GEN-LAST:event_btn_abrirMouseExited

    private void btn_cargarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cargarMouseExited
        btn_cargar.setBackground(new Color(10,130,203));
    }//GEN-LAST:event_btn_cargarMouseExited

    private void btn_cargarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cargarMouseEntered
        btn_cargar.setBackground(new Color(8,105,165));
    }//GEN-LAST:event_btn_cargarMouseEntered
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Load_file dialog = new Load_file(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_cargar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private LIB.JTexfieldPH_FielTex ruta;
    // End of variables declaration//GEN-END:variables
}
