/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Users;
import SQL.Insertar;
import SQL.Select;
import Tools.Creador;
import Tools.StringHandling;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class Menu extends javax.swing.JFrame {
    
    Creador crea = new Creador();
    DefaultTableModel model;
    String nombre_nube;
    Boolean tabla_llena = false;
    String folder;
    Select sl = new Select();
    Insertar is = new Insertar();
    /**
     * Creates new form Menu
     */
 
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        crea.llenando_JComboBox_Nubes(jComboBoxNubes);
        jComboBoxNubes.setVisible(true);
        Jlabel_Nombre_Carpeta.setVisible(false);

        btn_add_folder.setVisible(true);
        btn_delete_folder.setVisible(false);
        
        //Info de lo que hace el boton
        btn_upload.setToolTipText("Cargar archivo");
        btn_add_folder.setToolTipText("Crear carpeta");
        Atras1.setToolTipText("Cerrar sesión");
    }
    
    public Menu(String nombre_carpeta) {
        initComponents();
        this.setLocationRelativeTo(null);
        jComboBoxNubes.setVisible(false);
        Jlabel_Nombre_Carpeta.setVisible(true);

        btn_add_folder.setVisible(false);
        btn_delete_folder.setVisible(true);
        
        Jlabel_Nombre_Carpeta.setText(nombre_carpeta);
        folder = nombre_carpeta;
        
        //Info de lo que hace el boton
        btn_upload.setToolTipText("Cargar archivo");
        btn_delete_folder.setToolTipText("Eliminar Carpeta");
        Atras1.setToolTipText("Cerrar sesión");
        
        // Aca llenamos la tabla, con los archivos que estan dentro de la carpeta
        //crea.add_Info_Table_Menu(model,jTable_Archivos, nombre_nube);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Atras1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_add_folder = new javax.swing.JButton();
        btn_delete_folder = new javax.swing.JButton();
        btn_upload = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Archivos = new javax.swing.JTable();
        jComboBoxNubes = new javax.swing.JComboBox<>();
        Jlabel_Nombre_Carpeta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(205, 205, 205));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Aplicación CLIENTE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 660, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Nube_Link.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 80));

        Atras1.setBackground(new java.awt.Color(10, 144, 203));
        Atras1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Atras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/close_icon.png"))); // NOI18N
        Atras1.setBorder(null);
        Atras1.setBorderPainted(false);
        Atras1.setContentAreaFilled(false);
        Atras1.setFocusPainted(false);
        Atras1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/close_icon_G.png"))); // NOI18N
        Atras1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/close_icon_G.png"))); // NOI18N
        Atras1.setVerifyInputWhenFocusTarget(false);
        Atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras1ActionPerformed(evt);
            }
        });
        jPanel1.add(Atras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 40, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(10, 144, 203));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_add_folder.setBackground(new java.awt.Color(10, 144, 203));
        btn_add_folder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_add_folder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_folder.png"))); // NOI18N
        btn_add_folder.setBorder(null);
        btn_add_folder.setBorderPainted(false);
        btn_add_folder.setContentAreaFilled(false);
        btn_add_folder.setFocusPainted(false);
        btn_add_folder.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_folder_G.png"))); // NOI18N
        btn_add_folder.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_folder_G.png"))); // NOI18N
        btn_add_folder.setVerifyInputWhenFocusTarget(false);
        btn_add_folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_folderActionPerformed(evt);
            }
        });
        jPanel3.add(btn_add_folder, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -10, 80, 70));

        btn_delete_folder.setBackground(new java.awt.Color(10, 144, 203));
        btn_delete_folder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_delete_folder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_folder_icon.png"))); // NOI18N
        btn_delete_folder.setBorder(null);
        btn_delete_folder.setBorderPainted(false);
        btn_delete_folder.setContentAreaFilled(false);
        btn_delete_folder.setFocusPainted(false);
        btn_delete_folder.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_folder_icon_G.png"))); // NOI18N
        btn_delete_folder.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_folder_icon_G.png"))); // NOI18N
        btn_delete_folder.setVerifyInputWhenFocusTarget(false);
        btn_delete_folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_folderActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete_folder, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -10, 80, 70));

        btn_upload.setBackground(new java.awt.Color(10, 144, 203));
        btn_upload.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/upload_icon.png"))); // NOI18N
        btn_upload.setBorder(null);
        btn_upload.setBorderPainted(false);
        btn_upload.setContentAreaFilled(false);
        btn_upload.setFocusPainted(false);
        btn_upload.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/upload_icon_G.png"))); // NOI18N
        btn_upload.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/upload_icon_G.png"))); // NOI18N
        btn_upload.setVerifyInputWhenFocusTarget(false);
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });
        jPanel3.add(btn_upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -10, 80, 70));

        jPanel4.setBackground(new java.awt.Color(10, 144, 203));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        jTable_Archivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Archivo", "Peso (Kb)", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ArchivosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Archivos);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 530, 140));

        jComboBoxNubes.setBackground(new java.awt.Color(205, 205, 205));
        jComboBoxNubes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Nube" }));
        jComboBoxNubes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNubesItemStateChanged(evt);
            }
        });
        jComboBoxNubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNubesActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxNubes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 160, -1));

        Jlabel_Nombre_Carpeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Jlabel_Nombre_Carpeta.setText(" ");
        jPanel3.add(Jlabel_Nombre_Carpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 148, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Carpeta: ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 660, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_ArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ArchivosMouseClicked
        model = (DefaultTableModel) jTable_Archivos.getModel();
        String archivo_o_carpeta = model.getValueAt(jTable_Archivos.getSelectedRow(), 2).toString();
        if (archivo_o_carpeta.equals("Archivo")){  //Aca se habre el Jframe de Modal_file_options
            String nombre_file = model.getValueAt(jTable_Archivos.getSelectedRow(), 0).toString();
            Modal_file_options open = null;
            String info[]= new String[2];
            info = sl.getCloudInfo(jComboBoxNubes.getSelectedItem().toString());
            open = new Modal_file_options(this,true,nombre_file,info[0],nombre_nube);
            open.setVisible(true);
       }else{   //Aca se habre el Jframe de los archivos que estan dentro de la carpeta
            String nombre_carpeta = model.getValueAt(jTable_Archivos.getSelectedRow(), 0).toString();
            System.out.println(nombre_carpeta);
            Menu open = null;
            open = new Menu(nombre_carpeta);
            open.setVisible(true);
        }
    }//GEN-LAST:event_jTable_ArchivosMouseClicked

    private void jComboBoxNubesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNubesItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxNubes.getSelectedIndex() > 0 && tabla_llena  != true){
//            
//            //Aca llanaremos la Tabla con los archivos de la nube que el usuario selecciono
//            nombre_nube =  jComboBoxNubes.getSelectedItem().toString();
//            
//            crea.add_Info_Table_Menu(model,jTable_Archivos, nombre_nube,"192.168.0.102", "Angel", "redes");
//            tabla_llena = true;  //Por alguna razon si no coloco lo de tabla llena, se llena la tabla dos veces con lo que hay en el servidor
//            
////            jTextFieldNube.setText(obtener);
////            System.out.println(jComboBoxNubes.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxNubesItemStateChanged

    private void jComboBoxNubesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNubesActionPerformed
        crea.limpiarTabla(jTable_Archivos);
        if (jComboBoxNubes.getSelectedIndex() != 0){
        crea.limpiarTabla(jTable_Archivos);
        crea.add_Info_Table_Menu(model, jTable_Archivos, jComboBoxNubes.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBoxNubesActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        if (jComboBoxNubes.getSelectedIndex() != 0){
            Load_file open = null;
            String info[]= new String[2];
            info = sl.getCloudInfo(jComboBoxNubes.getSelectedItem().toString());
            open = new Load_file(this,true,info[0],info[1]);
            open.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Para poder CARGAR, primero debe seleccionar la nube.", "Precaución 👀",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_uploadActionPerformed

    private void btn_delete_folderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_folderActionPerformed
          int respuesta= JOptionPane.showConfirmDialog(null,"Seguro que quiere Eliminar la Carpeta '"+folder+"'?","Eliminar",JOptionPane.YES_NO_OPTION);
        if (respuesta == 0){
            this.dispose();
            JOptionPane.showMessageDialog(null, "Ha sido eliminada la carpeta.", "Exito",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_delete_folderActionPerformed

    private void btn_add_folderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_folderActionPerformed
        Create_folder open = null;
        open = new Create_folder(this,true);
        open.setVisible(true);
    }//GEN-LAST:event_btn_add_folderActionPerformed

    private void Atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras1ActionPerformed
        int respuesta= JOptionPane.showConfirmDialog(null,"Seguro quiere salir cerrar sesión?","Salir",JOptionPane.YES_NO_OPTION);
        if (respuesta == 0){
            is.insertF_fin(new Users().getID());
            Login open = null;
            open = new Login();
            open.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Atras1ActionPerformed

//los archivos de la nube que el usuario selecciono
//            nombre_nube =  jComboBoxNubes.getSelectedItem().toString();
//            
//            crea.add_Info_Table_Menu(model,jTable_Archivos, nombre_nube,"192.168.0.102", "Angel", "redes");
//            tabla_llena = true;  //Por alguna razon si no coloco lo de tabla llena, se llena la tabla dos veces con lo que hay en el servidor
//            
////            jTextFieldNube.setText(obtener);
////            System.out.println(jComboBoxNubes.getSelectedIndex());
//        }
//    }                                                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras1;
    private javax.swing.JLabel Jlabel_Nombre_Carpeta;
    private javax.swing.JButton btn_add_folder;
    private javax.swing.JButton btn_delete_folder;
    private javax.swing.JButton btn_upload;
    private javax.swing.JComboBox<String> jComboBoxNubes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Archivos;
    // End of variables declaration//GEN-END:variables
}
