/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.Creador;
import Tools.StringHandling;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class Menu extends javax.swing.JFrame {
    
    Creador crea = new Creador();
    DefaultTableModel model;
    String nombre_nube;
    
    /**
     * Creates new form Menu
     */
 
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        crea.llenando_JComboBox_Nubes(jComboBoxNubes);
        
        //Info de lo que hace el boton
        btn_upload.setToolTipText("Cargar archivo");
        btn_add_folder.setToolTipText("Crear carpeta");
        Atras.setToolTipText("Cerrar sesión");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_upload = new javax.swing.JButton();
        btn_add_folder = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Archivos = new javax.swing.JTable();
        jComboBoxNubes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Atras.setBackground(new java.awt.Color(10, 144, 203));
        Atras.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_icon.png"))); // NOI18N
        Atras.setBorder(null);
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setFocusPainted(false);
        Atras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_icon_G.png"))); // NOI18N
        Atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_icon_G.png"))); // NOI18N
        Atras.setVerifyInputWhenFocusTarget(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 40, 30));

        jPanel5.setBackground(new java.awt.Color(205, 205, 205));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Aplicación CLIENTE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 660, 20));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nube_Link.png"))); // NOI18N
        jPanel2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jLabel1.setBackground(new java.awt.Color(10, 144, 203));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(10, 144, 203));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        btn_upload.setBackground(new java.awt.Color(10, 144, 203));
        btn_upload.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upload_icon.png"))); // NOI18N
        btn_upload.setBorder(null);
        btn_upload.setBorderPainted(false);
        btn_upload.setContentAreaFilled(false);
        btn_upload.setFocusPainted(false);
        btn_upload.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upload_icon_G.png"))); // NOI18N
        btn_upload.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upload_icon_G.png"))); // NOI18N
        btn_upload.setVerifyInputWhenFocusTarget(false);
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });
        jPanel3.add(btn_upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -10, 100, 70));

        btn_add_folder.setBackground(new java.awt.Color(10, 144, 203));
        btn_add_folder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_add_folder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_folder.png"))); // NOI18N
        btn_add_folder.setBorder(null);
        btn_add_folder.setBorderPainted(false);
        btn_add_folder.setContentAreaFilled(false);
        btn_add_folder.setFocusPainted(false);
        btn_add_folder.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_folder_G.png"))); // NOI18N
        btn_add_folder.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_folder_G.png"))); // NOI18N
        btn_add_folder.setVerifyInputWhenFocusTarget(false);
        btn_add_folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_folderActionPerformed(evt);
            }
        });
        jPanel3.add(btn_add_folder, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, -10, 110, 70));

        jTable_Archivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Archivo", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ArchivosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Archivos);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 530, 140));

        jComboBoxNubes.setBackground(new java.awt.Color(205, 205, 205));
        jComboBoxNubes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Nube" }));
        jComboBoxNubes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNubesItemStateChanged(evt);
            }
        });
        jComboBoxNubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNubesActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxNubes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 160, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 660, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        int respuesta= JOptionPane.showConfirmDialog(null,"Seguro quiere salir cerrar sesión?","Salir",JOptionPane.YES_NO_OPTION);
        if (respuesta == 0){
            Login open = null;
            open = new Login();
            open.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AtrasActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        
        if (jComboBoxNubes.getSelectedIndex() != 0){
            Load_file open = null;
            open = new Load_file(this,true);
            open.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Para poder CARGAR, primero debe seleccionar la nube.", "Precaución 👀",JOptionPane.WARNING_MESSAGE);
        }
        
       
    }//GEN-LAST:event_btn_uploadActionPerformed

    private void btn_add_folderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_folderActionPerformed
        Create_folder open = null;
        open = new Create_folder(this,true);
        open.setVisible(true);
    }//GEN-LAST:event_btn_add_folderActionPerformed

    private void jTable_ArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ArchivosMouseClicked
        StringHandling localFile = new StringHandling();
        
        model = (DefaultTableModel) jTable_Archivos.getModel();
        String nombre_file = model.getValueAt(jTable_Archivos.getSelectedRow(), 0).toString();
        String peso_file = model.getValueAt(jTable_Archivos.getSelectedRow(), 1).toString();        
        String type_file = model.getValueAt(jTable_Archivos.getSelectedRow(), 2).toString();

//
//        jTextFieldNube.setText(localFile.getFileName_OR_Type(nombre_file,1));           
//        jTextFieldNube1.setText(type_file);
//        
        Modal_file_options open = null;
        open = new Modal_file_options(this,true,nombre_file+type_file,nombre_nube);
        open.setVisible(true);
    }//GEN-LAST:event_jTable_ArchivosMouseClicked

    private void jComboBoxNubesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNubesItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxNubes.getSelectedIndex() > 0){
            
            //Aca llanaremos la Tabla con los archivos de la nube que el usuario selecciono
            nombre_nube =  jComboBoxNubes.getSelectedItem().toString();
            
            crea.add_Info_Table_Menu(model,jTable_Archivos, nombre_nube);
            
            
//            jTextFieldNube.setText(obtener);
//            System.out.println(jComboBoxNubes.getSelectedIndex());
        }
    }//GEN-LAST:event_jComboBoxNubesItemStateChanged

    private void jComboBoxNubesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNubesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNubesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btn_add_folder;
    private javax.swing.JButton btn_upload;
    private javax.swing.JComboBox<String> jComboBoxNubes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Archivos;
    // End of variables declaration//GEN-END:variables
}
