/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Tools.Creador;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel
 */
public class Share_file extends javax.swing.JDialog {
    
    Creador crea = new Creador();
    String file_Name;
    String nube_Name;
    String user_name;
    String ip_address;

    /**
     * Creates new form Share_file
     */
    public Share_file(JDialog padre, boolean modo) {
        super(padre, modo);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Share_file(JDialog padre, boolean modo, String fileName, String nubeName, String ip_address) {
        super(padre, modo);
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.file_Name = fileName;
        this.nube_Name = nubeName;
        this.ip_address = ip_address;
        
        jLabel_NameFile.setText("Archivo: "+file_Name);        
        jLabel_NameNube.setText("Nube: "+nube_Name);
        
        crea.llenando_JComboBox_Users(jComboBoxUsers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxUsers = new javax.swing.JComboBox<>();
        btn_compartir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jLabel_NameFile = new javax.swing.JLabel();
        jLabel_NameNube = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxUsers.setBackground(new java.awt.Color(205, 205, 205));
        jComboBoxUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el user" }));
        jComboBoxUsers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxUsersItemStateChanged(evt);
            }
        });
        jComboBoxUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUsersActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 240, 30));

        btn_compartir.setBackground(new java.awt.Color(10, 130, 203));
        btn_compartir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_compartir.setForeground(new java.awt.Color(0, 0, 0));
        btn_compartir.setText("Compartir");
        btn_compartir.setToolTipText("");
        btn_compartir.setBorderPainted(false);
        btn_compartir.setContentAreaFilled(false);
        btn_compartir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_compartir.setFocusPainted(false);
        btn_compartir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_compartir.setName(""); // NOI18N
        btn_compartir.setOpaque(true);
        btn_compartir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_compartir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_compartirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_compartirMouseExited(evt);
            }
        });
        btn_compartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compartirActionPerformed(evt);
            }
        });
        jPanel3.add(btn_compartir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 140));

        jPanel4.setBackground(new java.awt.Color(205, 205, 205));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, 20));

        Atras.setBackground(new java.awt.Color(10, 144, 203));
        Atras.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_icon.png"))); // NOI18N
        Atras.setBorder(null);
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setFocusPainted(false);
        Atras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_icon_G.png"))); // NOI18N
        Atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back_icon_G.png"))); // NOI18N
        Atras.setVerifyInputWhenFocusTarget(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 30, 30));

        jLabel_NameFile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel_NameFile.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NameFile.setText("FileName");
        jPanel1.add(jLabel_NameFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, -1));

        jLabel_NameNube.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel_NameNube.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NameNube.setText("NubeName");
        jPanel1.add(jLabel_NameNube, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, -1));

        jLabel4.setBackground(new java.awt.Color(10, 144, 203));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 10));

        jLabel3.setBackground(new java.awt.Color(10, 144, 203));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("    Compartir archivo:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_compartirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_compartirMouseEntered
        btn_compartir.setBackground(new Color(8,105,165));
    }//GEN-LAST:event_btn_compartirMouseEntered

    private void btn_compartirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_compartirMouseExited
        btn_compartir.setBackground(new Color(10,130,203));
    }//GEN-LAST:event_btn_compartirMouseExited

    private void btn_compartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compartirActionPerformed
        if (jComboBoxUsers.getSelectedIndex() != 0){
            int respuesta= JOptionPane.showConfirmDialog(null,"Seguro quere compartir el archivo de nombre"+file_Name+"?","Salir",JOptionPane.YES_NO_OPTION);
            if (respuesta == 0){

                //Aca vala logica para hacer el compartido del archivo

                this.dispose();
            }   
        }else{
            JOptionPane.showMessageDialog(null, "Primero tiene que seleccionar el User a compartir.", "Precaución 👀",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_compartirActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void jComboBoxUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUsersActionPerformed

    private void jComboBoxUsersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUsersItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxUsers.getSelectedIndex() > 0){

            //Aca se selecciona el nombre del usuario
            user_name =  jComboBoxUsers.getSelectedItem().toString();

            //Luego se hace la logica para enviarlo al user
            
        }
    }//GEN-LAST:event_jComboBoxUsersItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Share_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Share_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Share_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Share_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Share_file dialog = new Share_file(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton btn_compartir;
    private javax.swing.JComboBox<String> jComboBoxUsers;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_NameFile;
    private javax.swing.JLabel jLabel_NameNube;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
